# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName(_fromUtf8("dialog"))
        dialog.resize(696, 382)
        self.gridLayout = QtGui.QGridLayout(dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.groupBox_4 = QtGui.QGroupBox(dialog)
        self.groupBox_4.setMinimumSize(QtCore.QSize(200, 200))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_initialImage = QtGui.QLabel(self.groupBox_4)
        self.label_initialImage.setObjectName(_fromUtf8("label_initialImage"))
        self.gridLayout_4.addWidget(self.label_initialImage, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(dialog)
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 200))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_finalImage = QtGui.QLabel(self.groupBox_3)
        self.label_finalImage.setObjectName(_fromUtf8("label_finalImage"))
        self.gridLayout_5.addWidget(self.label_finalImage, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_3)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.groupBox = QtGui.QGroupBox(dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.horizontalSlider_lowHue = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_lowHue.setMaximum(179)
        self.horizontalSlider_lowHue.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_lowHue.setObjectName(_fromUtf8("horizontalSlider_lowHue"))
        self.horizontalLayout.addWidget(self.horizontalSlider_lowHue)
        self.spinBox_lowHue = QtGui.QSpinBox(self.groupBox)
        self.spinBox_lowHue.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_lowHue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_lowHue.setMaximum(179)
        self.spinBox_lowHue.setObjectName(_fromUtf8("spinBox_lowHue"))
        self.horizontalLayout.addWidget(self.spinBox_lowHue)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalSlider_lowSat = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_lowSat.setMaximum(255)
        self.horizontalSlider_lowSat.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_lowSat.setObjectName(_fromUtf8("horizontalSlider_lowSat"))
        self.horizontalLayout_2.addWidget(self.horizontalSlider_lowSat)
        self.spinBox_lowSat = QtGui.QSpinBox(self.groupBox)
        self.spinBox_lowSat.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_lowSat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_lowSat.setMaximum(255)
        self.spinBox_lowSat.setObjectName(_fromUtf8("spinBox_lowSat"))
        self.horizontalLayout_2.addWidget(self.spinBox_lowSat)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.horizontalSlider_lowVal = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_lowVal.setMaximum(255)
        self.horizontalSlider_lowVal.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_lowVal.setObjectName(_fromUtf8("horizontalSlider_lowVal"))
        self.horizontalLayout_3.addWidget(self.horizontalSlider_lowVal)
        self.spinBox_lowVal = QtGui.QSpinBox(self.groupBox)
        self.spinBox_lowVal.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_lowVal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_lowVal.setMaximum(255)
        self.spinBox_lowVal.setObjectName(_fromUtf8("spinBox_lowVal"))
        self.horizontalLayout_3.addWidget(self.spinBox_lowVal)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.horizontalSlider_highHue = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider_highHue.setMaximum(179)
        self.horizontalSlider_highHue.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_highHue.setObjectName(_fromUtf8("horizontalSlider_highHue"))
        self.horizontalLayout_4.addWidget(self.horizontalSlider_highHue)
        self.spinBox_highHue = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_highHue.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_highHue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_highHue.setMaximum(179)
        self.spinBox_highHue.setObjectName(_fromUtf8("spinBox_highHue"))
        self.horizontalLayout_4.addWidget(self.spinBox_highHue)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(50, 0))
        self.label_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.horizontalSlider_highSat = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider_highSat.setMaximum(255)
        self.horizontalSlider_highSat.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_highSat.setObjectName(_fromUtf8("horizontalSlider_highSat"))
        self.horizontalLayout_5.addWidget(self.horizontalSlider_highSat)
        self.spinBox_highSat = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_highSat.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_highSat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_highSat.setMaximum(255)
        self.spinBox_highSat.setObjectName(_fromUtf8("spinBox_highSat"))
        self.horizontalLayout_5.addWidget(self.spinBox_highSat)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(50, 0))
        self.label_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.horizontalSlider_highVal = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider_highVal.setMaximum(255)
        self.horizontalSlider_highVal.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_highVal.setObjectName(_fromUtf8("horizontalSlider_highVal"))
        self.horizontalLayout_6.addWidget(self.horizontalSlider_highVal)
        self.spinBox_highVal = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_highVal.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_highVal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_highVal.setMaximum(255)
        self.spinBox_highVal.setObjectName(_fromUtf8("spinBox_highVal"))
        self.horizontalLayout_6.addWidget(self.spinBox_highVal)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_loadImage = QtGui.QPushButton(dialog)
        self.pushButton_loadImage.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_loadImage.setObjectName(_fromUtf8("pushButton_loadImage"))
        self.verticalLayout_3.addWidget(self.pushButton_loadImage)
        self.pushButton_close = QtGui.QPushButton(dialog)
        self.pushButton_close.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_close.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 4);"))
        self.pushButton_close.setObjectName(_fromUtf8("pushButton_close"))
        self.verticalLayout_3.addWidget(self.pushButton_close)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        dialog.setWindowTitle(_translate("dialog", "HSV Filter", None))
        self.groupBox_4.setTitle(_translate("dialog", "Initial Image", None))
        self.label_initialImage.setText(_translate("dialog", "TextLabel", None))
        self.groupBox_3.setTitle(_translate("dialog", "Final Image", None))
        self.label_finalImage.setText(_translate("dialog", "TextLabel", None))
        self.groupBox.setTitle(_translate("dialog", "Lower threshold", None))
        self.label.setText(_translate("dialog", "Hue", None))
        self.label_2.setText(_translate("dialog", "Sat", None))
        self.label_3.setText(_translate("dialog", "Val", None))
        self.groupBox_2.setTitle(_translate("dialog", "Higher threshold", None))
        self.label_4.setText(_translate("dialog", "Hue", None))
        self.label_5.setText(_translate("dialog", "Sat", None))
        self.label_6.setText(_translate("dialog", "Val", None))
        self.pushButton_loadImage.setText(_translate("dialog", "Load Image", None))
        self.pushButton_close.setText(_translate("dialog", "Close", None))

